from enum import Enum, unique

from discord.app_commands import locale_str


@unique
class LoggedEventTypeID(Enum):
    TEXT_PIECE_EDITED = "TEXT_PIECE_EDITED"
    ROUTE_TARGET_UPDATED = "ROUTE_TARGET_UPDATED"
    ROUTE_TOGGLED = "ROUTE_TOGGLED"
    PARAMETER_EDITED = "PARAMETER_EDITED"
    PERMISSION_BOUND = "PERMISSION_BOUND"
    PERMISSION_UNBOUND = "PERMISSION_UNBOUND"
    ROLE_CLEARED_FROM_PERMISSIONS = "ROLE_CLEARED_FROM_PERMISSIONS"
    USER_PREFERENCE_UPDATED = "USER_PREFERENCE_UPDATED"
    USER_COOLDOWN_UPDATED = "USER_COOLDOWN_UPDATED"
    LEVEL_COOLDOWN_UPDATED = "LEVEL_COOLDOWN_UPDATED"
    REQUEST_INITIALIZED = "REQUEST_INITIALIZED"
    REQUEST_REQUESTED = "REQUEST_REQUESTED"
    REQUEST_OPINION_ADDED = "REQUEST_OPINION_ADDED"
    REQUEST_RESOLUTION_ADDED = "REQUEST_RESOLUTION_ADDED"
    TRAINEE_REVIEW_ADDED = "TRAINEE_REVIEW_ADDED"
    TRAINEE_REVIEW_RESOLVED = "TRAINEE_REVIEW_RESOLVED"
    TRAINEE_PROMOTED = "TRAINEE_PROMOTED"
    TRAINEE_EXPELLED = "TRAINEE_EXPELLED"


@unique
class TextPieceID(Enum):
    COMMON_SUCCESS = "common.success"
    COMMON_LANGUAGE_SELECTION_PROPOSAL_SUBTEXT = "common.language_selection_proposal_subtext"
    COMMON_NOT_SPECIFIED = "common.not_specified"
    PERMISSION_NO_ASSIGNED_ROLES = "permission.no_assigned_roles"
    PERMISSION_MEMBER_HAS_NO_PERMISSIONS = "permission.member_has_no_permissions"
    PAGINATION_TOP_REACHED = "pagination.top_reached"
    PAGINATION_BOTTOM_REACHED = "pagination.bottom_reached"
    PAGINATION_NO_ENTRIES = "pagination.no_entries"
    COOLDOWN_OVERWRITE_CONFIRMATION = "cooldown.overwrite_confirmation"
    COOLDOWN_NOT_ON_COOLDOWN = "cooldown.not_on_cooldown"
    COOLDOWN_INFO = "cooldown.info"
    HELP_DURATION = "help.duration"
    HELP_TIMESTAMP = "help.timestamp"
    LOG_NO_FILTERS = "log.no_filters"
    LOG_EMPTY_FILTER = "log.empty_filter"
    LOG_EMPTY_FILTER_WONT_BE_SAVED = "log.empty_filter_wont_be_saved"
    REQUEST_MODAL_TITLE = "request_modal.title"
    REQUEST_MODAL_YT_LINK_LABEL = "request_modal.yt_link.label"
    REQUEST_MODAL_ADDITIONAL_COMMENT_LABEL = "request_modal.additional_comment.label"
    REQUEST_MODAL_ADDITIONAL_COMMENT_PLACEHOLDER = "request_modal.additional_comment.placeholder"
    REQUEST_MODAL_INVALID_YT_LINK = "request_modal.invalid_yt_link"
    REQUEST_PENDING_WIDGET_OPINION_ALREADY_EXISTS = "request_pending_widget.opinion_already_exists"
    REQUEST_PENDING_WIDGET_REVIEW_ALREADY_EXISTS = "request_pending_widget.review_already_exists"
    REQUEST_PENDING_WIDGET_TRAINEE_REVIEW_REQUIRED = "request_pending_widget.trainee_review_required"
    REQUEST_RESOLUTION_WIDGET_RESOLUTION_ALREADY_EXISTS = "request_resolution_widget.resolution_already_exists"
    REQUEST_OPINION_MODAL_TITLE = "request_opinion_modal.title"
    REQUEST_OPINION_MODAL_REASON_LABEL = "request_opinion_modal.reason.label"
    REQUEST_OPINION_MODAL_REASON_PLACEHOLDER = "request_opinion_modal.reason.placeholder"
    REQUEST_OPINION_MODAL_REVIEW_LABEL = "request_opinion_modal.review.label"
    REQUEST_OPINION_MODAL_REVIEW_PLACEHOLDER = "request_opinion_modal.review.placeholder"
    REQUEST_COMMAND_SUBMITTED = "request_command.submitted"
    REQUEST_COMMAND_CLOSED = "request_command.closed"
    REQUEST_COMMAND_ALREADY_RATED = "request_command.already_rated"
    REQUEST_COMMAND_NOT_FOUND = "request_command.not_found"
    REQUEST_COMMAND_ALREADY_APPROVED = "request_command.already_approved"
    REQUEST_COMMAND_PREVIOUS_PENDING = "request_command.previous_pending"
    REQUEST_COMMAND_USER_ON_COOLDOWN = "request_command.user_on_cooldown"
    REQUEST_COMMAND_USER_BANNED_TEMPORARILY = "request_command.user_banned_temporarily"
    REQUEST_COMMAND_USER_BANNED_FOREVER = "request_command.user_banned_forever"
    REQUEST_COMMAND_LEVEL_ON_COOLDOWN = "request_command.level_on_cooldown"
    REQUEST_COMMAND_LEVEL_BANNED_TEMPORARILY = "request_command.level_banned_temporarily"
    REQUEST_COMMAND_LEVEL_BANNED_FOREVER = "request_command.level_banned_forever"
    REQUEST_REVIEW = "request.review"
    REQUEST_SUMMARY_GOOD = "request.review.summary.good"
    REQUEST_SUMMARY_BAD = "request.review.summary.bad"
    REQUEST_APPROVED = "request.approved"
    REQUEST_GRADE_STARRATE = "request.approved.grade.starrate"
    REQUEST_GRADE_FEATURED = "request.approved.grade.featured"
    REQUEST_GRADE_EPIC = "request.approved.grade.epic"
    REQUEST_GRADE_MYTHIC = "request.approved.grade.mythic"
    REQUEST_GRADE_LEGENDARY = "request.approved.grade.legendary"
    REQUEST_REJECTED = "request.rejected"
    REQUEST_INFO_REVIEWERS_WIDGET_LINK_TEXT = "request_info.reviewers_widget_link_text"
    REQUEST_INFO_MODERATORS_WIDGET_LINK_TEXT = "request_info.moderators_widget_link_text"
    REQUEST_INFO_REQUEST_NOT_FOUND = "request_info.request_not_found"
    REQUEST_NO_IGNORED = "request.no_ignored"
    REQUEST_NO_UNRESOLVED = "request.no_unresolved"
    REQUEST_NO_REVIEWS = "request.no_reviews"
    REQUEST_INSERT_COMMAND_CREATOR_MUST_BE_SPECIFIED = "request_insert_command.creator_must_be_specified"
    TRAINEE_REVIEW_MODAL_TITLE = "trainee_review_modal.title"
    TRAINEE_REVIEW_MODAL_FEEDBACK_LABEL = "trainee_review_modal.feedback.label"
    TRAINEE_REVIEW_MODAL_FEEDBACK_PLACEHOLDER = "trainee_review_modal.feedback.placeholder"
    TRAINEE_REVIEW_RESOLUTION_RESPONSE_FEW_REVIEWS = "trainee_review.resolution_response.few_reviews"
    TRAINEE_REVIEW_RESOLUTION_RESPONSE_PROMOTION_READY = "trainee_review.resolution_response.promotion_ready"
    TRAINEE_REVIEW_RESOLUTION_RESPONSE_PROMOTE_BTN_LABEL = "trainee_review.resolution_response.promote_btn_label"
    TRAINEE_REVIEW_RESOLUTION_RESPONSE_EXPEL_BTN_LABEL = "trainee_review.resolution_response.expel_btn_label"
    TRAINEE_REVIEW_RESOLUTION_RESPONSE_WAIT_BTN_LABEL = "trainee_review.resolution_response.wait_btn_label"
    TRAINEE_PROMOTION_NOT_A_TRAINEE = "trainee_promotion.not_a_trainee"
    TRAINEE_PROMOTION_ROLE_NOT_ASSOCIATED = "trainee_promotion.role_not_associated"
    TRAINEE_PICK_NO_REQUESTS = "trainee_pick.no_requests"
    QUEUE_QUEUE_CLOSED_ERROR = "queue.queue_closed_error"
    QUEUE_INFO = "queue.info"
    QUEUE_INFO_OPEN_HEADER = "queue.info.open_header"
    QUEUE_INFO_CLOSED_HEADER = "queue.info.closed_header"
    QUEUE_INFO_DISABLED = "queue.info.disabled"
    CONFIRMATION_OVERRIDE_FILTER = "confirmation.override_filter"
    CONFIRMATION_DELETE_FILTER = "confirmation.delete_filter"
    WARNING_NO_EFFECT = "warning.no_effect"
    ERROR_COMPONENT_ERROR = "error.component_error"
    ERROR_COMMAND_ERROR = "error.command_error"
    ERROR_FORBIDDEN = "error.forbidden"
    ERROR_FILTER_DOESNT_EXIST = "error.filter_doesnt_exist"
    ERROR_CANT_PARSE_TIMESTAMP = "error.cant_parse_timestamp"
    ERROR_CANT_REMOVE_ADMIN_PERMISSION = "error.cant_remove_admin_permission"
    ERROR_WRONG_PARAMETER_VALUE_TYPE = "error.wrong_parameter_value_type"
    ERROR_BAD_DURATION_FORMAT = "error.bad_duration_format"
    ERROR_ORIGIN_COOLDOWN_ENDLESS = "error.origin_cooldown_endless"
    ERROR_COOLDOWN_END_IN_PAST = "error.cooldown_end_in_past"
    ERROR_REPORT_NO_DATA = "error.report_no_data"
    COMMAND_DESCRIPTION_REQUEST_CREATE = "command_description.request.create"
    COMMAND_DESCRIPTION_REQUEST_WIDGETS = "command_description.request.widgets"
    COMMAND_DESCRIPTION_REQUEST_IGNORED = "command_description.request.ignored"
    COMMAND_DESCRIPTION_REQUEST_UNRESOLVED = "command_description.request.unresolved"
    COMMAND_DESCRIPTION_REQUEST_INSERT = "command_description.request.insert"
    COMMAND_DESCRIPTION_BACKUP_SAVE = "command_description.backup.save"
    COMMAND_DESCRIPTION_BACKUP_LOAD = "command_description.backup.load"
    COMMAND_DESCRIPTION_LANGUAGE = "command_description.language"
    COMMAND_DESCRIPTION_HELP_DURATION = "command_description.help.duration"
    COMMAND_DESCRIPTION_HELP_TIMESTAMP = "command_description.help.timestamp"
    COMMAND_DESCRIPTION_LEVELCD_LIST = "command_description.levelcd.list"
    COMMAND_DESCRIPTION_LEVELCD_DESCRIBE = "command_description.levelcd.describe"
    COMMAND_DESCRIPTION_LEVELCD_AMEND = "command_description.levelcd.amend"
    COMMAND_DESCRIPTION_LEVELCD_UPDATE = "command_description.levelcd.update"
    COMMAND_DESCRIPTION_LEVELCD_HISTORY = "command_description.levelcd.history"
    COMMAND_DESCRIPTION_USERCD_LIST = "command_description.usercd.list"
    COMMAND_DESCRIPTION_USERCD_DESCRIBE = "command_description.usercd.describe"
    COMMAND_DESCRIPTION_USERCD_AMEND = "command_description.usercd.amend"
    COMMAND_DESCRIPTION_USERCD_UPDATE = "command_description.usercd.update"
    COMMAND_DESCRIPTION_USERCD_HISTORY = "command_description.usercd.history"
    COMMAND_DESCRIPTION_LOG_RESTRICT_USER = "command_description.log.restrict_user"
    COMMAND_DESCRIPTION_LOG_RESTRICT_TYPE = "command_description.log.restrict_type"
    COMMAND_DESCRIPTION_LOG_RESTRICT_CUSTOM_FIELD = "command_description.log.restrict_custom_field"
    COMMAND_DESCRIPTION_LOG_UNRESTRICT_USER = "command_description.log.unrestrict_user"
    COMMAND_DESCRIPTION_LOG_UNRESTRICT_TYPE = "command_description.log.unrestrict_type"
    COMMAND_DESCRIPTION_LOG_UNRESTRICT_CUSTOM_FIELD = "command_description.log.unrestrict_custom_field"
    COMMAND_DESCRIPTION_LOG_CLEAR_CUSTOM_FIELD_RESTRICTIONS = "command_description.log.clear_custom_field_restrictions"
    COMMAND_DESCRIPTION_LOG_CLEAR_FILTER = "command_description.log.clear_filter"
    COMMAND_DESCRIPTION_LOG_DESCRIBE_FILTER = "command_description.log.describe_filter"
    COMMAND_DESCRIPTION_LOG_VIEW = "command_description.log.view"
    COMMAND_DESCRIPTION_LOG_LIST_FILTERS = "command_description.log.list_filters"
    COMMAND_DESCRIPTION_LOG_SELECT_FILTER = "command_description.log.select_filter"
    COMMAND_DESCRIPTION_LOG_SAVE_FILTER = "command_description.log.save_filter"
    COMMAND_DESCRIPTION_LOG_DELETE_FILTER = "command_description.log.delete_filter"
    COMMAND_DESCRIPTION_PARAMETER_DESCRIBE = "command_description.parameter.describe"
    COMMAND_DESCRIPTION_PARAMETER_SET = "command_description.parameter.set"
    COMMAND_DESCRIPTION_PARAMETER_RESET = "command_description.parameter.reset"
    COMMAND_DESCRIPTION_PARAMETER_LIST = "command_description.parameter.list"
    COMMAND_DESCRIPTION_PERMISSION_LIST_FLAGS = "command_description.permission.list_flags"
    COMMAND_DESCRIPTION_PERMISSION_BIND = "command_description.permission.bind"
    COMMAND_DESCRIPTION_PERMISSION_UNBIND = "command_description.permission.unbind"
    COMMAND_DESCRIPTION_PERMISSION_CLEAR = "command_description.permission.clear"
    COMMAND_DESCRIPTION_PERMISSION_LIST_ROLES = "command_description.permission.list_roles"
    COMMAND_DESCRIPTION_PERMISSION_DESCRIBE_MEMBER = "command_description.permission.describe_member"
    COMMAND_DESCRIPTION_QUEUE_OPEN = "command_description.queue.open"
    COMMAND_DESCRIPTION_QUEUE_CLOSE = "command_description.queue.close"
    COMMAND_DESCRIPTION_QUEUE_INFO = "command_description.queue.info"
    COMMAND_DESCRIPTION_QUEUE_HISTORY = "command_description.queue.history"
    COMMAND_DESCRIPTION_REVIEWS_LEVEL = "command_description.reviews.level"
    COMMAND_DESCRIPTION_REVIEWS_USER = "command_description.reviews.user"
    COMMAND_DESCRIPTION_ROUTE_DESCRIBE = "command_description.route.describe"
    COMMAND_DESCRIPTION_ROUTE_UPDATE_CHANNEL = "command_description.route.update_channel"
    COMMAND_DESCRIPTION_ROUTE_RESET_CHANNEL = "command_description.route.reset_channel"
    COMMAND_DESCRIPTION_ROUTE_ENABLE = "command_description.route.enable"
    COMMAND_DESCRIPTION_ROUTE_DISABLE = "command_description.route.disable"
    COMMAND_DESCRIPTION_ROUTE_LIST = "command_description.route.list"
    COMMAND_DESCRIPTION_TEXT_DESCRIBE = "command_description.text.describe"
    COMMAND_DESCRIPTION_TEXT_EDIT = "command_description.text.edit"
    COMMAND_DESCRIPTION_TEXT_RESET = "command_description.text.reset"
    COMMAND_DESCRIPTION_TEXT_LIST = "command_description.text.list"
    COMMAND_DESCRIPTION_TRAINEE_PROMOTE = "command_description.trainee.promote"
    COMMAND_DESCRIPTION_TRAINEE_EXPEL = "command_description.trainee.expel"
    COMMAND_DESCRIPTION_TRAINEE_PICK = "command_description.trainee.pick"
    COMMAND_DESCRIPTION_REPORT_NEW_REQUESTS = "command_description.report.new_requests"
    COMMAND_DESCRIPTION_REPORT_PENDING_REQUESTS = "command_description.report.pending_requests"
    COMMAND_DESCRIPTION_REPORT_REVIEWER_OPINIONS = "command_description.report.reviewer_opinions"
    COMMAND_DESCRIPTION_REPORT_REVIEW_ACTIVITY = "command_description.report.review_activity"
    COMMAND_OPTION_REQUEST_CREATE_LEVEL_ID = "command_option.request.create.level_id"
    COMMAND_OPTION_REQUEST_WIDGETS_LEVEL_ID = "command_option.request.widgets.level_id"
    COMMAND_OPTION_REQUEST_INSERT_LEVEL_ID = "command_option.request.insert.level_id"
    COMMAND_OPTION_REQUEST_INSERT_LANGUAGE = "command_option.request.insert.language"
    COMMAND_OPTION_REQUEST_INSERT_YT_LINK = "command_option.request.insert.yt_link"
    COMMAND_OPTION_REQUEST_INSERT_CREATOR_MENTION = "command_option.request.insert.creator_mention"
    COMMAND_OPTION_REQUEST_INSERT_CREATOR_NAME = "command_option.request.insert.creator_name"
    COMMAND_OPTION_REQUEST_INSERT_ADDITIONAL_COMMENT = "command_option.request.insert.additional_comment"
    COMMAND_OPTION_BACKUP_LOAD_FILE = "command_option.backup.load.file"
    COMMAND_OPTION_LANGUAGE_LANGUAGE = "command_option.language.language"
    COMMAND_OPTION_LEVELCD_LIST_COOLDOWN_LISTING_TYPE = "command_option.levelcd.list.cooldown_listing_type"
    COMMAND_OPTION_LEVELCD_DESCRIBE_LEVEL_ID = "command_option.levelcd.describe.level_id"
    COMMAND_OPTION_LEVELCD_AMEND_LEVEL_ID = "command_option.levelcd.amend.level_id"
    COMMAND_OPTION_LEVELCD_AMEND_REASON = "command_option.levelcd.amend.reason"
    COMMAND_OPTION_LEVELCD_UPDATE_LEVEL_ID = "command_option.levelcd.update.level_id"
    COMMAND_OPTION_LEVELCD_UPDATE_DURATION = "command_option.levelcd.update.duration"
    COMMAND_OPTION_LEVELCD_UPDATE_REASON = "command_option.levelcd.update.reason"
    COMMAND_OPTION_LEVELCD_HISTORY_LEVEL_ID = "command_option.levelcd.history.level_id"
    COMMAND_OPTION_USERCD_LIST_COOLDOWN_LISTING_TYPE = "command_option.usercd.list.cooldown_listing_type"
    COMMAND_OPTION_USERCD_DESCRIBE_USER = "command_option.usercd.describe.user"
    COMMAND_OPTION_USERCD_AMEND_USER = "command_option.usercd.amend.user"
    COMMAND_OPTION_USERCD_AMEND_REASON = "command_option.usercd.amend.reason"
    COMMAND_OPTION_USERCD_UPDATE_USER = "command_option.usercd.update.user"
    COMMAND_OPTION_USERCD_UPDATE_DURATION = "command_option.usercd.update.duration"
    COMMAND_OPTION_USERCD_UPDATE_REASON = "command_option.usercd.update.reason"
    COMMAND_OPTION_USERCD_HISTORY_USER = "command_option.usercd.history.user"
    COMMAND_OPTION_LOG_RESTRICT_USER_USER = "command_option.log.restrict_user.user"
    COMMAND_OPTION_LOG_RESTRICT_TYPE_EVENT_TYPE = "command_option.log.restrict_type.event_type"
    COMMAND_OPTION_LOG_RESTRICT_CUSTOM_FIELD_KEY = "command_option.log.restrict_custom_field.key"
    COMMAND_OPTION_LOG_RESTRICT_CUSTOM_FIELD_VALUE = "command_option.log.restrict_custom_field.value"
    COMMAND_OPTION_LOG_UNRESTRICT_CUSTOM_FIELD_KEY = "command_option.log.unrestrict_custom_field.key"
    COMMAND_OPTION_LOG_DESCRIBE_FILTER_NAME = "command_option.log.describe_filter.name"
    COMMAND_OPTION_LOG_VIEW_TIMESTAMP = "command_option.log.view.timestamp"
    COMMAND_OPTION_LOG_SELECT_FILTER_NAME = "command_option.log.select_filter.name"
    COMMAND_OPTION_LOG_SAVE_FILTER_NAME = "command_option.log.save_filter.name"
    COMMAND_OPTION_LOG_DELETE_FILTER_NAME = "command_option.log.delete_filter.name"
    COMMAND_OPTION_PARAMETER_DESCRIBE_PARAMETER = "command_option.parameter.describe.parameter"
    COMMAND_OPTION_PARAMETER_SET_PARAMETER = "command_option.parameter.set.parameter"
    COMMAND_OPTION_PARAMETER_SET_NEW_VALUE = "command_option.parameter.set.new_value"
    COMMAND_OPTION_PARAMETER_RESET_PARAMETER = "command_option.parameter.reset.parameter"
    COMMAND_OPTION_PERMISSION_BIND_PERMISSION = "command_option.permission.bind.permission"
    COMMAND_OPTION_PERMISSION_BIND_ROLE = "command_option.permission.bind.role"
    COMMAND_OPTION_PERMISSION_UNBIND_PERMISSION = "command_option.permission.unbind.permission"
    COMMAND_OPTION_PERMISSION_UNBIND_ROLE = "command_option.permission.unbind.role"
    COMMAND_OPTION_PERMISSION_CLEAR_ROLE = "command_option.permission.clear.role"
    COMMAND_OPTION_PERMISSION_DESCRIBE_MEMBER_MEMBER = "command_option.permission.describe_member.member"
    COMMAND_OPTION_REVIEWS_LEVEL_LEVEL_ID = "command_option.reviews.level.level_id"
    COMMAND_OPTION_REVIEWS_USER_AUTHOR = "command_option.reviews.user.author"
    COMMAND_OPTION_ROUTE_DESCRIBE_ROUTE = "command_option.route.describe.route"
    COMMAND_OPTION_ROUTE_UPDATE_CHANNEL_ROUTE = "command_option.route.update_channel.route"
    COMMAND_OPTION_ROUTE_UPDATE_CHANNEL_NEW_VALUE = "command_option.route.update_channel.new_value"
    COMMAND_OPTION_ROUTE_RESET_CHANNEL_ROUTE = "command_option.route.reset_channel.route"
    COMMAND_OPTION_ROUTE_ENABLE_ROUTE = "command_option.route.enable.route"
    COMMAND_OPTION_ROUTE_DISABLE_ROUTE = "command_option.route.disable.route"
    COMMAND_OPTION_TEXT_DESCRIBE_TEMPLATE_NAME = "command_option.text.describe.template_name"
    COMMAND_OPTION_TEXT_EDIT_TEMPLATE_NAME = "command_option.text.edit.template_name"
    COMMAND_OPTION_TEXT_EDIT_LANGUAGE = "command_option.text.edit.language"
    COMMAND_OPTION_TEXT_EDIT_NEW_VALUE = "command_option.text.edit.new_value"
    COMMAND_OPTION_TEXT_RESET_TEMPLATE_NAME = "command_option.text.reset.template_name"
    COMMAND_OPTION_TEXT_RESET_LANGUAGE = "command_option.text.reset.language"
    COMMAND_OPTION_TRAINEE_PROMOTE_TRAINEE = "command_option.trainee.promote.trainee"
    COMMAND_OPTION_TRAINEE_EXPEL_TRAINEE = "command_option.trainee.expel.trainee"
    COMMAND_OPTION_REPORT_NEW_REQUESTS_DATE_FROM = "command_option.report.new_requests.date_from"
    COMMAND_OPTION_REPORT_NEW_REQUESTS_DATE_TO = "command_option.report.new_requests.date_to"
    COMMAND_OPTION_REPORT_NEW_REQUESTS_GRANULARITY = "command_option.report.new_requests.granularity"
    COMMAND_OPTION_REPORT_PENDING_REQUESTS_DATE_FROM = "command_option.report.pending_requests.date_from"
    COMMAND_OPTION_REPORT_PENDING_REQUESTS_DATE_TO = "command_option.report.pending_requests.date_to"
    COMMAND_OPTION_REPORT_PENDING_REQUESTS_GRANULARITY = "command_option.report.pending_requests.granularity"
    COMMAND_OPTION_REPORT_REVIEWER_OPINIONS_REVIEWER = "command_option.report.reviewer_opinions.reviewer"
    COMMAND_OPTION_REPORT_REVIEWER_OPINIONS_DATE_FROM = "command_option.report.reviewer_opinions.date_from"
    COMMAND_OPTION_REPORT_REVIEWER_OPINIONS_DATE_TO = "command_option.report.reviewer_opinions.date_to"
    COMMAND_OPTION_REPORT_REVIEW_ACTIVITY_DATE_FROM = "command_option.report.review_activity.date_from"
    COMMAND_OPTION_REPORT_REVIEW_ACTIVITY_DATE_TO = "command_option.report.review_activity.date_to"
    COMMAND_OPTION_REPORT_REVIEW_ACTIVITY_GRANULARITY = "command_option.report.review_activity.granularity"
    COMMAND_CHOICE_COOLDOWN_LISTING_TEMPORARY = "command_choice.cooldown_listing.temporary"
    COMMAND_CHOICE_COOLDOWN_LISTING_ENDLESS = "command_choice.cooldown_listing.endless"
    COMMAND_CHOICE_REPORT_GRANULARITY_DAY = "command_choice.report_granularity.day"
    COMMAND_CHOICE_REPORT_GRANULARITY_WEEK = "command_choice.report_granularity.week"

    def as_locale_str(self) -> locale_str:
        return locale_str(self.value)


@unique
class RouteID(Enum):
    LOG = "log"
    PENDING_REQUEST = "pending_request"
    RESOLUTION = "resolution"
    APPROVAL_NOTIFICATION = "approval_notification"
    REJECTION_NOTIFICATION = "rejection_notification"
    REVIEW_TEXT = "review_text"
    TRAINEE_REVIEW_TEXT = "trainee_review_text"
    REQUESTS_CLOSED = "requests_closed"
    REQUESTS_REOPENED = "requests_reopened"
    ARCHIVE = "archive"
    STREAM_START_ANNOUNCEMENT = "stream_start_announcement"
    STREAM_END_GOODBYE = "stream_end_goodbye"


@unique
class ParameterID(Enum):
    QUEUE_BLOCK_AT = "queue.block_at"
    QUEUE_UNBLOCK_AT = "queue.unblock_at"
    QUEUE_BLOCK_ENABLED = "queue.block_enabled"
    QUEUE_UNBLOCK_ENABLED = "queue.unblock_enabled"
    QUEUE_BLOCKED = "queue.blocked"
    COOLDOWN_POST_REQUEST_USER_CD = "cooldown.post_request_user_cd"
    COOLDOWN_POST_REJECT_LEVEL_CD = "cooldown.post_reject_level_cd"
    REQUEST_APPEND_CONCLUSION_TO_REVIEW = "request.append_conclusion_to_review"
    TRAINEE_RESOLVED_REVIEWS_FOR_PROMOTION_DECISION = "trainee.resolved_reviews_for_promotion_decision"


@unique
class PermissionFlagID(Enum):
    ADMIN = "admin"
    LOG_VIEWER = "log_viewer"
    REPORT_VIEWER = "report_viewer"
    REVIEWER = "reviewer"
    TRAINEE = "trainee"
    TRAINEE_SUPERVISOR = "trainee_supervisor"
    GD_MOD = "gd_mod"
    BAN_LEVELS = "ban_levels"
    BAN_USERS = "ban_users"
    NO_REQUEST_COOLDOWN = "no_request_cooldown"
    REQUEST_WHILE_QUEUE_CLOSED = "request_while_queue_closed"
    INSERT_REQUESTS = "insert_requests"
    REMOVE_OTHER_LEVEL_BANS = "remove_other_level_bans"
    REMOVE_OTHER_USER_BANS = "remove_other_user_bans"


@unique
class StageParameterID(Enum):
    GUILD_ID = "guild_id"
    SPEAKS_RUSSIAN_ROLE_ID = "speaks_russian_role_id"
    ADMIN_USER_ID = "admin_user_id"
    DEVELOPER_USER_IDS = "developer_user_ids"


@unique
class UserPreferenceID(Enum):
    LANGUAGE = "language"